### ISSUE TITLE
你好，能指点一下你打包的过程修改了什么配置吗？我打包的apk无内容显示，拜托了？

### ISSUE THREAD

**Issue by franklin-repo** [akFace/vue-movie#3]
我的修改如下，希望大神能给点意见
1、index.html文件

<script type="text/javascript" src="cordova.js"></script>

2、main.js
window.document.addEventListener('deviceready',` function() { new Vue({ router, store, render: h => h(AppView) }).$mount('#app') window.navigator.splashscreen.hide() }, false);

3、config下的index.js
assetsSubDirectory: '', 
assetsPublicPath: '',

**Comment by akFace** [comment]
@18979687252 
1、无需放到deviceready中执行，
2、执行npm run build，build后的代码本地浏览器可以直接打开吗

**Comment by franklin-repo** [comment]
本地不能在浏览器里运行

**Comment by akFace** [comment]
@18979687252  
那你的配置弄错了，默认的配置就好了.
1、config 下的index.js
![image](https://user-images.githubusercontent.com/22288837/31976901-b38c98ae-b96c-11e7-8b38-b1eaa6419862.png)
2、main.js文件
![image](https://user-images.githubusercontent.com/22288837/31976936-04c98b96-b96d-11e7-9056-066c03692803.png)

**Comment by franklin-repo** [comment]
apk还是没有内容，应该是出错了。
我用cordova run browser 运行，发现只有本地资源的加载，外网接口有跨域问题，虽然通过cordova-plugin-whitelist数据请求成功，但是报错了
`Failed to load http://webapi.rightpsy.com/api/Active/GetActiveList?pageIndex=1&pageSize=10: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

**Comment by akFace** [comment]
只你只要弄成本地浏览器可以直接打开，那么打包成apk肯定可以打开的
关键配置，你弄成这样，再重新 npm run build 
![image](https://user-images.githubusercontent.com/22288837/31983089-606afbe4-b98e-11e7-8cd7-efa468b5aca6.png)

**Comment by franklin-repo** [comment]
大哥，按照你的配置搞了，总感觉姿势不对，从未成功过。很无语，如果有空帮忙看看
[https://github.com/18979687252/letian](url)

**Comment by akFace** [comment]
项目没有了，忘了看了 ε=(´ο｀*)))唉
